name: nf-CRISPR-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Add required software dependencies here
  - fastqc=0.11.8
  - python=2.7.15
  - monotonic=1.5
  - multiqc=1.8
  - r-base=3.6.2
