name: crispr-1.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastqc=0.11.8
  - python=3.8.1
  - numpy=1.17.5
  - regex
  - biopython=1.76
  - multiqc=1.8
  - r-base=3.6.2
  - r-markdown=0.9
