#
# RNA-seq config for MultiQC
#
#################################################################

skip_generalstats: true
read_count_multiplier: 0.000001
read_count_prefix: 'M'
read_count_desc: 'millions'

custom_data:
    my_stats:
        file_format: 'csv'
        section_name: 'Basic Metrics'
        description: ' on aligned data'
        plot_type: 'table'
        pconfig:
            namespace: 'stats'
            title: 'Aligned reads'
            id: 'stats'
            scale: 'RdYlBu'
            format: '{:,.2f}'
            save_file: true

    gene_type:
       file_format: 'csv'
       section_name: 'Expressed Genes'
       description: 'with a TPM value > 1 are considered. The number of expressed genes per sample was splitted into the 5 most abundant classes following the known gene annotations.'
       plot_type: 'bargraph'
       pconfig:
            namespace: 'genetype'
            id: 'genetype'
            title: 'Expressed Genes'
            ylab: 'Number of expressed genes (TPM>1)'
            scale: 'Pastel1'

    gene_saturation:
       file_format: 'tsv'
       section_name: 'Gene-based saturation'
       description: 'plot showing the number of detected genes for a given set of subsampling values.'
       plot_type: 'linegraph'
       pconfig:
            namespace: 'gene saturation'
            id: 'genesaturation'
            title: 'Gene-based Saturation'
            ylab: 'Number of detected genes'
            xlab: 'Number of reads'

sp:
   my_stats:
      fn: '*.stats'
   gene_type:
      fn: '*genetype.txt'
   gene_saturation:
      fn: '*gcurve.txt'

module_order:
  - fastqc
  - bowtie1:
      name: 'rRNA Mapping'
      info: 'This section reports the fraction of reads aligned on ribosomal RNAs.'
      target: ''
      path_filters:
        - '*.log'
  - star
  - hisat2
  - tophat
  - rseqc
  - featureCounts
  - HTSeq
  - preseq:
     name: 'Sequencing Complexity'
     info: 'estimates the complexity of a library, showing how many additional unique reads are sequenced for increasing total read count. A shallow curve indicates complexity saturation. The dashed line shows a perfectly complex library where total reads = unique reads. The presented graph shows extrapolated curves up to 200M sequencing reads.'

report_section_order:
  stats:
    order: 1
  gene_saturation:
    order: -400
  gene_type:
    order: -500
  DupRadar:
    order: -600 
  sample-pca:
    order: -800
  sample-correlation:
    order: -900
  software_versions:
    order: -1000
  summary:
    order: -1100

table_columns_visible:
    FastQC:
        percent_duplicates: False
    stats:
        Number_of_aligned_reads: False
        Number_of_duplicates: False
        Number_of_uniquely_aligned_reads: False
        Number_of_multiple_aligned_reads: False
        Number_of_rRNA: False

preseq:
   notrim: true

plots_force_interactive: True
