#
#  CRISPR config for MultiQC
#
#################################################################

skip_generalstats: true
read_count_multiplier: 0.000001
read_count_prefix: 'M'
read_count_desc: 'millions'

###################################
## Custom content

custom_data:
    my_stats:
        file_format: 'csv'
        section_name: 'General Metrics'
        description: ' of sequenced data.'
        plot_type: 'table'
        pconfig:
            namespace: 'stats'
            id: 'stats'
            title: 'General Statistics'
            save_file: true
            #col1_header: 'Sample ID'
        headers:
            sample_name:
              title: 'Sample Name'
              scale: false
              format: '{:.0f}'
              placement: 2000
            num_reads:
              title: 'Total Reads'
              scale: 'YlGnBu'
              format: '{:,.0f}'
              placement: 4000
            num_reads_with_guide:
              title: 'Reads with guide'
              scale: 'YlGnBu'
              format: '{:,.0f}'
              hidden: true
              placement: 5000
            perc_mapped_reads:
              title: 'Mapped reads (%)'
              min: 0
              max: 100
              scale: 'RdYlGn'
              suffix: '%'
              format: '{:,.1f}'
              placement: 6000
            perc_undetected_guides:
              title: 'Undetected guides (%)'
              min: 0
              max: 100
              scale: 'RdYlGn-rev'
              suffix: '%'
              format: '{:,.1f}'
              placement: 7000
            skew_ratio:
              title: 'Skew ratio'
              scale: 'RdYlGn-rev'
              format: '{:,.0f}'
              placement: 8000
            sgRNA_library_size:
              title: 'sgRNA library size'
              scale: 'RdYlGn-rev'
              format: '{:,.0f}'
              placement: 9000


sp:
   my_stats:
      fn: '*.stats'

table_cond_formatting_rules:
    perc_mapped_reads:
        pass:
            - gt: 80
        warn:
            - lt: 80
        fail:
            - lt: 65
    perc_undetected_guides:
        pass:
            - lt: 25
        warn:
            - lt: 40
        fail:
            - gt: 40

###############################
## Modules 

module_order:
  - fastqc

#############################
## Display

report_section_order:
  stats:
    order: 1
  software_versions:
    order: -1000
  summary:
    order: -1100

table_columns_visible:
    FastQC:
        percent_duplicates: False

plots_force_interactive: True
